# Generated by Django 2.2.4 on 2019-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookbook',
            name='chef',
        ),
        migrations.AddField(
            model_name='cookbook',
            name='editor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cookbook',
            name='year_published',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='retailer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cookbook',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
