# Generated by Django 2.2.4 on 2019-08-07 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0002_auto_20190807_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='year_published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
