# Generated by Django 2.2.4 on 2019-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook_app', '0003_auto_20190807_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
